sudo: required
language: ruby

services:
  - docker

before_install:
  - docker pull nishiki/ansible:stretch

script:
  - rake

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
